name: ml
channels:
  - defaults
  - apple
  - conda-forge
dependencies:
 - pip
 - ipython
 - jupyter
 - numpy
 - scipy
 - pandas
 - matplotlib
 - tensorflow-deps
 - pip:
   - tensorflow-macos
   - -r requirements.txt
